# Trial Exclusion Analysis
We examine the proportion of trials excluded by different exclusion criteria, and how these proportions differ across trial categories `Color`/`BW`/`Noise BG`.

In [1]:
import pandas as pd
import polars as pl
from pymer4.models import glmer
import plotly.io as pio

import config as cnfg
import analysis.helpers.funnels.funnel_config as fcnfg
from analysis.helpers.read_data import read_data
from analysis.helpers.funnels.trial_inclusion import check_trial_inclusion_criteria
from analysis.helpers.visualizations.funnel.category_comparison import category_comparison_figure

pio.renderers.default = "browser"      # or "browser"

Error importing in API mode: ImportError('On Windows, cffi mode "ANY" is only "ABI".')
Trying to import in ABI mode.

### Load Data

In [2]:
loaded_data = read_data(cnfg.OUTPUT_PATH, drop_bad_eye=True, drop_outliers=True)
metadata = loaded_data.metadata
fixations = loaded_data.fixations
actions = loaded_data.actions
idents = loaded_data.identifications
del loaded_data

### Apply Inclusion/Exclusion Criteria

In [3]:
inclusion_criteria = check_trial_inclusion_criteria(
    metadata, fixations, actions, idents,
    min_gaze_coverage=fcnfg.DEFAULT_GAZE_COVERAGE_PERCENT_THRESHOLD,
    min_fixation_rate=fcnfg.DEFAULT_FIXATION_RATE_THRESHOLD,
    bad_actions=fcnfg.DEFAULT_BAD_ACTIONS,
    require_actions=False,
)

# merge with trial category and target count
inclusion_criteria = inclusion_criteria.merge(
    metadata[["subject", "trial", "trial_category"]],
    on=["subject", "trial"],
    how="left"
)

print(f"Overall inclusion rate: {100 * inclusion_criteria['is_valid_trial'].mean():.2f}%")

Overall inclusion rate: 85.00%

### Inclusion by Trial Category
We check which trial category results in more excluded trials, regardless of the exclusion criterion.

In [4]:
inclusion_by_subject = inclusion_criteria.groupby('subject')['is_valid_trial'].agg(['mean', 'std', 'sem'])
inclusion_by_subject["trial_category"] = "ALL"
inclusion_by_subject_and_category = inclusion_criteria.groupby(['subject', 'trial_category'])['is_valid_trial'].agg(['mean', 'std', 'sem']).reset_index()
inclusion_by_category = pd.concat([inclusion_by_subject.reset_index(), inclusion_by_subject_and_category])

inclusion_by_category_subject_average = inclusion_criteria.groupby('trial_category')['is_valid_trial'].agg(['mean', 'std', 'sem']) * 100

In [5]:
trial_category_fig = category_comparison_figure(
    inclusion_by_category.reset_index(),
    categ_col="trial_category",
    title="Trial Inclusion Rate by Trial Category",
    yaxis_title="Inclusion Rate (%)",
    show_distributions=True,
    show_individuals=True,
    show_mean=True,
)

display(inclusion_by_category_subject_average)
trial_category_fig.show()

                 mean        std       sem
trial_category
BW              80.00  40.083595  2.587385
COLOR           88.75  31.664097  2.043909
NOISE           86.25  34.509413  2.227573

#### Statistical Analysis: Does trial category predict trial inclusion?
We use a mixed-effects logistic regression model to test whether trial category significantly predicts trial inclusion, while accounting for subject-level variability.<br>
Our model is specified as:
$$logit(P[\text{is\_valid\_trial} = 1]) = \beta_0 + \beta_1 \cdot C(\text{trial\_category}) + (1 | \text{subject})$$

In [6]:
model = glmer(
    formula="is_valid_trial ~ C(trial_category) + (1 | subject)",
    data=pl.from_pandas(inclusion_criteria),
    family="binomial"
)
model.set_factors({
    "subject": (
        pd.Series(inclusion_criteria["subject"].unique())
        .sort_values()
        .map(str, na_action="ignore")
        .to_list()
    ),
    "trial_category": (
        pd.Series(inclusion_criteria["trial_category"].unique())
        .sort_values()
        .tolist()
    ),
})
result = model.fit(summary=True, exponentiate=False)

print("Pairwise Comtrasts:")
display(model.emmeans("trial_category", contrasts="pairwise", p_adjust="tukey"))
result

Pairwise Comtrasts:

shape: (3, 9)
┌───────────────┬────────────┬──────────┬─────┬───┬───────────┬──────┬───────────┬──────────┐
│ contrast      ┆ odds_ratio ┆ SE       ┆ df  ┆ … ┆ asymp_UCL ┆ null ┆ z_ratio   ┆ p_value  │
│ ---           ┆ ---        ┆ ---      ┆ --- ┆   ┆ ---       ┆ ---  ┆ ---       ┆ ---      │
│ cat           ┆ f64        ┆ f64      ┆ f64 ┆   ┆ f64       ┆ f64  ┆ f64       ┆ f64      │
╞═══════════════╪════════════╪══════════╪═════╪═══╪═══════════╪══════╪═══════════╪══════════╡
│ BW / COLOR    ┆ 0.487391   ┆ 0.129465 ┆ inf ┆ … ┆ 0.90834   ┆ 1.0  ┆ -2.705621 ┆ 0.018697 │
│ BW / NOISE    ┆ 0.62012    ┆ 0.156813 ┆ inf ┆ … ┆ 1.121673  ┆ 1.0  ┆ -1.889638 ┆ 0.14164  │
│ COLOR / NOISE ┆ 1.272325   ┆ 0.358327 ┆ inf ┆ … ┆ 2.461834  ┆ 1.0  ┆ 0.855182  ┆ 0.668587 │
└───────────────┴────────────┴──────────┴─────┴───┴───────────┴──────┴───────────┴──────────┘

GT(_tbl_data=shape: (6, 10)
┌────────────────┬─────────────────┬──────────┬───────────┬───┬──────────┬──────┬──────────┬───────┐
│ rfx            ┆ param           ┆ estimate ┆ conf_low  ┆ … ┆ z_stat   ┆ df   ┆ p_value  ┆ stars │
│ ---            ┆ ---             ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---  ┆ ---      ┆ ---   │
│ str            ┆ str             ┆ f64      ┆ f64       ┆   ┆ f64      ┆ f64  ┆ str      ┆ str   │
╞════════════════╪═════════════════╪══════════╪═══════════╪═══╪══════════╪══════╪══════════╪═══════╡
│ subject-sd     ┆ (Intercept)     ┆ 0.6339   ┆ null      ┆ … ┆ null     ┆ null ┆ null     ┆ null  │
│ null           ┆ null            ┆ null     ┆ null      ┆ … ┆ null     ┆ null ┆ null     ┆ null  │
│ Fixed Effects: ┆ null            ┆ null     ┆ null      ┆ … ┆ null     ┆ null ┆ null     ┆ null  │
│ null           ┆ (Intercept)     ┆ 1.501037 ┆ 1.010554  ┆ … ┆ 5.998132 ┆ inf  ┆ <.001    ┆ ***   │
│ null           ┆ C(trial_categor ┆ 0.718688 ┆ 0.198067  ┆ … ┆ 2.705621 ┆ inf  ┆ 0.006818 ┆ **    │
│                ┆ y)COLOR         ┆          ┆           ┆   ┆          ┆      ┆          ┆       │
│ null           ┆ C(trial_categor ┆ 0.477842 ┆ -0.017784 ┆ … ┆ 1.889638 ┆ inf  ┆ 0.05881  ┆ .     │
│                ┆ y)NOISE         ┆          ┆           ┆   ┆          ┆      ┆          ┆       │
└────────────────┴─────────────────┴──────────┴───────────┴───┴──────────┴──────┴──────────┴───────┘, _body=<great_tables._gt_data.Body object at 0x000001EE6C528C20>, _boxhead=Boxhead([ColInfo(var='rfx', type=<ColInfoTypeEnum.default: 1>, column_label='Random Effects:', column_align='left', column_width=None), ColInfo(var='param', type=<ColInfoTypeEnum.default: 1>, column_label='', column_align='left', column_width=None), ColInfo(var='estimate', type=<ColInfoTypeEnum.default: 1>, column_label='Estimate', column_align='right', column_width=None), ColInfo(var='conf_low', type=<ColInfoTypeEnum.default: 1>, column_label='CI-low', column_align='right', column_width=None), ColInfo(var='conf_high', type=<ColInfoTypeEnum.default: 1>, column_label='CI-high', column_align='right', column_width=None), ColInfo(var='std_error', type=<ColInfoTypeEnum.default: 1>, column_label='SE', column_align='right', column_width=None), ColInfo(var='z_stat', type=<ColInfoTypeEnum.default: 1>, column_label='Z-stat', column_align='right', column_width=None), ColInfo(var='df', type=<ColInfoTypeEnum.default: 1>, column_label='df', column_align='right', column_width=None), ColInfo(var='p_value', type=<ColInfoTypeEnum.default: 1>, column_label='p', column_align='left', column_width=None), ColInfo(var='stars', type=<ColInfoTypeEnum.default: 1>, column_label='', column_align='left', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x000001EE6C5293A0>, _spanners=Spanners([]), _heading=Heading(title='Formula: glmer(is_valid_trial~C(trial_category)+(1|subject))', subtitle=Md(text='Family: *binomial (link: *default*)*  \n            Number of observations: *720*  \n            Confidence intervals: *parametric*  \n            ---------------------  \n            Log-likelihood: *-290*  \n            AIC: *588* | BIC: *607*  \n            Residual error: *1.0*  \n        '), preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x000001EE6C52AAB0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x000001EE6C52A870>, _source_notes=[Md(text='Signif. codes: *0 *** 0.001 ** 0.01 * 0.05 . 0.1*')], _footnotes=[], _styles=[StyleInfo(locname=LocBody(columns=['param'], rows=None, mask=None), grpname=None, colname='param', rownum=0, colnum=None, styles=[CellStyleText(color=None, font=None, size=None, align=None, v_align=None, style='italic', weight=None, stretch=None, decorate=None, transform=None, whitespace=None)]), StyleInfo(locname=LocBody(columns=['param'], rows=None, mask=None), grpname=None, colname='param', rownum=1, colnum=None, styles=[CellStyleText(color=None, font=None, size=None, align=None, v_align=None, style='italic', weight=None, stretch=None, decorate=None, transform=None, whitespace=None)]), StyleInfo(locname=LocBody(columns=['param'], rows=None, mask=None), grpname=None, colname='param', rownum=2, colnum=None, styles=[CellStyleText(color=None, font=None, size=None, align=None, v_align=None, style='italic', weight=None, stretch=None, decorate=None, transform=None, whitespace=None)]), StyleInfo(locname=LocBody(columns=['param'], rows=None, mask=None), grpname=None, colname='param', rownum=3, colnum=None, styles=[CellStyleText(color=None, font=None, size=None, align=None, v_align=None, style='italic', weight=None, stretch=None, decorate=None, transform=None, whitespace=None)]), StyleInfo(locname=LocBody(columns=['param'], rows=None, mask=None), grpname=None, colname='param', rownum=4, colnum=None, styles=[CellStyleText(color=None, font=None, size=None, align=None, v_align=None, style='italic', weight=None, stretch=None, decorate=None, transform=None, whitespace=None)]), StyleInfo(locname=LocBody(columns=['param'], rows=None, mask=None), grpname=None, colname='param', rownum=5, colnum=None, styles=[CellStyleText(color=None, font=None, size=None, align=None, v_align=None, style='italic', weight=None, stretch=None, decorate=None, transform=None, whitespace=None)])], _locale=<great_tables._gt_data.Locale object at 0x000001EE6C5291C0>, _formats=[<great_tables._gt_data.FormatInfo object at 0x000001EE6C52B320>], _substitutions=[<great_tables._gt_data.FormatInfo object at 0x000001EE6C529010>], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='left'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='3px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='3px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='6px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='6px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='3px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='small'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

### Exclusion by Criteria
Now we examine the proportion of trials excluded by each criterion.<br>
Here, we don't care about the different trial categories, but rather the overall exclusion rates by each criterion.

In [7]:

inclusion_by_subject["trial_category"] = "ALL"
inclusion_by_subject_and_category = inclusion_criteria.groupby(['subject', 'trial_category'])['is_valid_trial'].agg(['mean', 'std', 'sem']).reset_index()
inclusion_by_category = pd.concat([inclusion_by_subject.reset_index(), inclusion_by_subject_and_category])

inclusion_by_category_subject_average = inclusion_criteria.groupby('trial_category')['is_valid_trial'].agg(['mean', 'std', 'sem']) * 100

In [8]:
inclusion_columns = [c for c in fcnfg.TRIAL_INCLUSION_CRITERIA if c in inclusion_criteria.columns]

inclusion_by_criterion_and_subject = (
    inclusion_criteria
    .groupby('subject')[inclusion_columns]
    .agg(['mean', 'std', 'sem'])
    .T.unstack(0).T
    .reset_index()
    .rename(columns={"level_1": "criterion"})
)

inclusion_by_criterion_average_subject = (
    inclusion_criteria[inclusion_columns + ["is_valid_trial"]]
    .agg(["mean", "std", "sem"])
    .T
    .reset_index()
    .rename(columns={"index": "criterion"})
)
inclusion_by_criterion_average_subject["subject"] = "ALL"

In [9]:
criterion_fig = category_comparison_figure(
    inclusion_by_criterion_and_subject.reset_index(),
    categ_col="criterion",
    title="Trial Inclusion Rate by Trial Category",
    yaxis_title="Inclusion Rate (%)",
    show_distributions=True,
    show_individuals=True,
    show_mean=True,
)

display(100 * inclusion_by_criterion_average_subject.set_index(["subject", "criterion"]))
criterion_fig.show()

                                        mean        std       sem
subject criterion
ALL     gaze_coverage             100.000000   0.000000  0.000000
        fixation_rate             100.000000   0.000000  0.000000
        no_bad_action              88.055556  32.453621  1.209475
        no_miss_with_false_alarm   95.972222  19.674664  0.733231
        is_valid_trial             85.000000  35.731965  1.331652